name: rsa_dart
description: A RSA trapdoor implementation
version: 1.0.0
repository: https://github.com/Minetest-j45/rsa_dart

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
dependencies:
  ninja_prime: ^2.0.0
